app:
  #name: serviceX -> should be set by app calling values
  version: not-versioned
  #namespace: same
  image:
    repository: kennethreitz/httpbin
    tag: latest
    port: 80
  env:
    APP_EXAMPLE_VAR: "hello"
  resources:
    requests:
      memory: "64Mi"
      cpu: "0.1"
    limits:
      memory: "128Mi"
      cpu: "0.5"

service:
  enabled: true
  port: 80
ingress:
  enabled: false

istio:
  enabled: false
  gateway:
    enabled: false
  virtualService:
    enabled: false
