---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.25.3
    helm:
      values: |
        service:
          type: NodePort
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
            nodePort: 30021
          - name: http2
            port: 80
            targetPort: 80
            nodePort: 30080
          - name: https
            port: 443
            targetPort: 443
            nodePort: 30443
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
