---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: v2.2.0
    helm:
      values: |
        auth:
          strategy: anonymous
        service:
          type: ClusterIP
        # deployment:
        #   custom_envs:
        #     - name: AWS_REGION
        #       value: {{ .Values.aws.region }}
        #     - name: AWS_CONFIG_FILE
        #       value: /root/.aws/credentials
        #   custom_secrets:
        #     - name: aws-credentials
        #       mount: /root/.aws/credentials
        # clustering:
        #   clusters:
        #     - name: remote-cluster
        #       secret_name: kiali-kubeconfig
        external_services:
          prometheus:
            url: {{ .Values.targetInfra.prometheus.url }}
          grafana:
            enabled: true
            internal_url: {{ .Values.targetInfra.grafana.url }}
          tracing:
            enabled: true
            internal_url: {{ .Values.targetInfra.jaeger.url }}
            provider: jaeger
            use_grpc: false
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - kiali.local

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  hosts:
    - kiali.local
  gateways:
    - kiali-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001
