---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jeremygovi/istio-sandbox
    targetRevision: {{ .Values.apps.ref }}
    path: apps/serviceX
    helm:
      values: |
        app:
          name: service-a
        ingress:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.apps.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
