apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-entrypoint
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: platform_apps
    repoURL: https://github.com/jeremygovi/istio-sandbox.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - Replace=true
