apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 1.72.0 # Remplacez par la version souhaitée
    helm:
      values: |
        auth:
          strategy: anonymous
        service:
          type: ClusterIP
        istioNamespace: istio-system
        istioComponents:
          istiod:
            enabled: true
            url: http://istiod.istio-system.svc:15014
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
