apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 15.0.0 # Remplacez par la version désirée du chart
    helm:
      values: |
        prometheus:
          enabled: true
          alertmanager:
            enabled: true
        server:
          global:
            scrape_interval: 15s
          service:
            type: ClusterIP
        pushgateway:
          enabled: true
        # Mount the node's root file system (/) at /host/root in the container
        hostRootFsMount:
          enabled: false
          # Defines how new mounts in existing mounts on the node or in the container
          # are propagated to the container or node, respectively. Possible values are
          # None, HostToContainer, and Bidirectional. If this field is omitted, then
          # None is used. More information on:
          # https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
          mountPropagation: HostToContainer
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
