apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: squid-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: squid
    targetRevision: 6.0.5 # Spécifiez la version stable souhaitée
    helm:
      values: |
        replicaCount: 1
        service:
          type: ClusterIP
          port: 3128
        auth:
          enabled: true
          existingSecret: squid-auth # Définit un Secret contenant les utilisateurs/mots de passe
        config:
          customConfig:
            - auth_param basic program /usr/lib/squid3/basic_ncsa_auth /opt/bitnami/squid/etc/passwd
            - auth_param basic children 5
            - auth_param basic realm "Squid Proxy Authentication"
            - auth_param basic credentialsttl 2 hours
            - acl authenticated proxy_auth REQUIRED
            - http_access allow authenticated
  destination:
    server: https://kubernetes.default.svc
    namespace: squid
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
