apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: squid-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://honestica.github.io/lifen-charts/
    chart: squid
    targetRevision: 0.4.3
    helm:
      values: |
        replicaCount: 1
        service:
          type: ClusterIP
          port: 3128
        config:
          squid:
            auth_param:
              basic:
                - program: /usr/lib/squid3/basic_ncsa_auth /etc/squid/passwd
                - realm: Squid Proxy Authentication
                - credentialsttl: 2 hours
                - children: 5
            acl:
              authenticated:
                - proxy_auth REQUIRED
            http_access:
              allow:
                - authenticated
        extraVolumes:
          - name: passwd
            secret:
              secretName: squid-auth
        extraVolumeMounts:
          - name: passwd
            mountPath: /etc/squid/passwd
            subPath: passwd
  destination:
    server: https://kubernetes.default.svc
    namespace: squid
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
