---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleetman
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: business-apps
spec:
  project: default
  source:
    repoURL: https://github.com/DickChesterwood/istio-fleetman
    targetRevision: master
    path: _course_files/arm64/warmup-exercise
    directory:
      include: "4-application-full-stack.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: fleetman
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleetman-ingress
  namespace: fleetman
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: fleetman.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleetman-webapp
                port:
                  number: 80
