---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-a
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: business-apps
spec:
  project: default
  source:
    repoURL: https://github.com/jeremygovi/istio-sandbox
    targetRevision: {{ .Values.apps.ref }}
    path: helm_charts/serviceX
    helm:
      values: |
        app:
          name: service-a
          namespace: {{ .Values.apps.namespace }}
        istio:
          enabled: true
          gateway:
            enabled: true
            hosts:
              - service-a.local
          virtualService:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.apps.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
