---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-b
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: business-apps
spec:
  project: default
  source:
    repoURL: https://github.com/jeremygovi/istio-sandbox
    targetRevision: {{ .Values.apps.ref }}
    path: helm_charts/serviceX
    helm:
      values: |
        app:
          name: service-b
          namespace: {{ .Values.apps.namespace }}
          image:
            repository: jeremygovi/devtool-box
            port: 3000
          env:
            APP_VERSION: 2
        istio:
          enabled: true
          gateway:
            enabled: true
            hosts:
              - service-b.local
          virtualService:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.apps.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
