# NOT FUNCTIONAL
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zipkin
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform-apps
spec:
  project: default
  source:
    repoURL: https://zipkin.io/zipkin-helm
    chart: zipkin
    targetRevision: 0.3.6
    helm:
      values: |
        xxx: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
