aws:
  region: eu-west-3

apps:
  ref: HEAD
  namespace: ivts

targetInfra:
  prometheus:
    # url: https://prometheus-evoyageurs-dev-paris.dev.aws.vsct.fr/
    url: http://prometheus-server.istio-system.svc.cluster.local:80
  grafana:
    url: http://grafana.istio-system.svc.cluster.local:80
  jaeger:
    url: http://jaeger-query.istio-system.svc.cluster.local:16686
