---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default "latest" }}"
          ports:
            - containerPort: {{ .Values.app.image.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-config
          resources:
{{ .Values.app.resources | toYaml | indent 12 }}
