{{- if .Values.istio.enabled }}
{{- if .Values.istio.gateway.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.app.name }}-gateway
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{ .Values.istio.gateway.port | default 80 }}
        name: http
        protocol: HTTP
      hosts:
{{- if .Values.istio.gateway.hosts }}
{{ toYaml .Values.istio.gateway.hosts | indent 8 }}
{{- else }}
        - "*"
{{- end }}
{{- end }}
{{- end }}
