---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.name }}-cert
  namespace: istio-system
  annotations:
      argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: {{ .Values.app.name }}-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{ with (first .Values.istio.gateway.hosts)  }}{{ . }}{{ end }}
  dnsNames:
  {{- if .Values.istio.gateway.hosts }}
  {{ toYaml .Values.istio.gateway.hosts | indent 4 }}
  {{- end }}
